module.exports = [
  {
    building: 'ILC',
    room: 'N151',
    access_notes: '',
    labels: [ 'WHITEBOARD', 'ACCESSIBLE', 'OUTLETS' ],
    capacity: 200,
  },
  {
    building: 'LIB',
    room: '1800',
    access_notes: '18th floor, accessible by elevator',
    labels: [ 'OUTLETS', 'WINDOWS' ],
    capacity: 54,
  },
  {
    building: 'WORC',
    room: '339',
    access_notes: '',
    labels: [ 'WHITEBOARD', 'OUTLETS', 'WINDOWS' ],
    capacity: 20,
  },
  {
    building: 'WORC',
    room: '347',
    access_notes: '',
    labels: [ 'OUTLETS', 'WHITEBOARD', 'WINDOWS' ],
    capacity: 10,
  },
  {
    building: 'WORC',
    room: '325',
    access_notes: '',
    labels: [ 'OUTLETS', 'WHITEBOARD', 'WINDOWS' ],
    capacity: 10,
  },
  {
    building: 'LIB',
    room: '2300',
    access_notes: '',
    labels: [ 'OUTLETS', 'WINDOWS' ],
    capacity: 48,
  },
  {
    building: 'LIB',
    room: '2100',
    access_notes: '',
    labels: [ 'OUTLETS', 'WINDOWS' ],
    capacity: 72,
  },
  {
    building: 'LIB',
    room: '2000',
    access_notes: '',
    labels: [ 'OUTLETS', 'QUIET_AREA', 'WINDOWS' ],
    capacity: 48,
  },
  {
    building: 'LIB',
    room: '1700',
    access_notes: '',
    labels: [ 'OUTLETS', 'WINDOWS', 'QUIET_AREA' ],
    capacity: 48,
  },
  {
    building: 'LIB',
    room: '1500',
    access_notes: '',
    labels: [ 'OUTLETS', 'WINDOWS' ],
    capacity: 50,
  },
  {
    building: 'LIB',
    room: '1100',
    access_notes: '',
    labels: [ 'OUTLETS', 'WINDOWS', 'QUIET_AREA' ],
    capacity: 48,
  },
  {
    building: 'LIB',
    room: '800',
    access_notes: '',
    labels: [ 'OUTLETS', 'WINDOWS', 'QUIET_AREA' ],
    capacity: 48,
  },
  {
    building: 'LGRT',
    room: 'T222',
    access_notes: '',
    labels: [ 'OUTLETS', 'WHITEBOARD' ],
    capacity: 30,
  },
  {
    building: 'LGRT',
    room: 'T220',
    access_notes: '',
    labels: [ 'OUTLETS', 'BAD_TEMP', 'WHITEBOARD' ],
    capacity: 20,
  },
  {
    building: 'LIB',
    room: '1400',
    access_notes: '',
    labels: [ 'QUIET_AREA', 'WINDOWS', 'OUTLETS' ],
    capacity: 48,
  },
  {
    building: 'ILC',
    room: 'S231',
    access_notes: '',
    labels: [ 'WHITEBOARD' ],
    capacity: 60,
  },
  {
    building: 'ILC',
    room: 'S211',
    access_notes: '',
    labels: [ 'OUTLETS', 'WHITEBOARD' ],
    capacity: 110,
  },
  {
    building: 'ILC',
    room: 'S311',
    access_notes: '',
    labels: [ 'OUTLETS', 'COMPUTERS', 'WHITEBOARD' ],
    capacity: 64,
  },
  {
    building: 'ILC',
    room: 'S331',
    access_notes: '',
    labels: [ 'OUTLETS', 'WHITEBOARD' ],
    capacity: 150,
  },
  {
    building: 'ILC',
    room: 'S110',
    access_notes: '',
    labels: [ 'OUTLETS', 'COMPUTERS', 'WHITEBOARD' ],
    capacity: 88,
  }
];